### ISSUE TITLE
Chat Bubbles

### ISSUE THREAD

**Issue by Avarisx** [SEELE1306/CSS-Snippets#12]
I originally got the chat bubble css from here 
(https://github.com/UzinSG/SEELE1306-CSS-Snippets/tree/main/Snippets/ChatBubbles) 

Then it stopped working properly as of today. When I went to go back to the link that I shared above it could no longer be found. But then I found the exact same one here, although when putting the chat bubble css you have here into discord, it still doesn't fully work.

The bubble works when images are uploaded and whatnot, but normal text messages do not have a bubble around the text. I have not touched anything with the code except for the colors which were working perfectly fine until now. And I even deleted the css file and did a fresh install without changing anything and it was still behaving the same way.
![Untitled](https://github.com/SEELE1306/CSS-Snippets/assets/9135464/aa78ed17-c55a-4cfc-9fbf-c6833cb50777)
![Untitled2](https://github.com/SEELE1306/CSS-Snippets/assets/9135464/74441f57-93a6-4a8d-b458-e2feefcd05ee)

**Comment by UzinSG** [comment]
The repo link above was created and deleted by me.
I deleted it after the pull request (temporary repo for fixing) was accepted.

You are correct that there is an error in ChatBubbles at the moment.

random class changes on the discord side or CSS source needs to be modified.

**Comment by Avarisx** [comment]
Ah, that makes sense. Well thank you for relaying this info to me, I appreciate it 🧡

And thank you for your work on this, I love it!
‎ 
‎ 
‎ 
Edit to your edit: 

Ohhhh, damn discord is always shutting down themes/snippets with "code" changes >_>

I don't know how CSS really works so I wouldn't know, and I do appreciate your work alongside many others who contribute to themes and snippets. So again, thank you for your time and patience for these kinds of customizations, I appreciate it.

**Comment by MomBon** [comment]
And thank you for you work on this, I love it

**Comment by UzinSG** [comment]
Hmm.... I thought it was a bug, but I guess it wasn't.
I got it working now and it's working fine ):

ChatBubbles, the one that gave you the problem, is fine.
The build you tested is the DEV build of Vencord. 

If after rechecking, the theme is fine, you can close the issue.

**Comment by Avarisx** [comment]
It's working, thank you again very much, you and the rest of the team are dope 🧡
