### ISSUE TITLE
Remove the border from the Usernames 🙏

### ISSUE THREAD

**Issue by yiruzu** [SEELE1306/CSS-Snippets#13]
![image](https://github.com/SEELE1306/CSS-Snippets/assets/94981325/728aecca-e637-4618-9250-5260f4da82b2)

**Comment by yiruzu** [comment]
*or make it optional

**Comment by CichyCze** [comment]
I'm currently using an older version of the Username and TimestampBubbles snippets because of that. At least some kind of optional "switch" would be lovely. It was way better before - decent, nice and not so distracting as the new look is.

**Comment by SEELE1306** [comment]
Hi, I will add the option to change back shortly.

**Comment by SEELE1306** [comment]
Can you check the import files again to see if the problems are solved?

**Comment by CichyCze** [comment]
Yeah, it works! Looks much better now ❤️
![image](https://github.com/SEELE1306/CSS-Snippets/assets/35575041/89f66757-dbd1-4c76-a043-2ce9c7eaba5d)
It would be even better with the not bolded text as it was before (see screenshot below) but this works too ^^
![image](https://github.com/SEELE1306/CSS-Snippets/assets/35575041/3a07576e-1599-494f-ad52-1baff23a3511)

**Comment by SEELE1306** [comment]
I commented out the `font-weight: bold` line. You can uncomment it in the code should you want it again in the future
